name: Generate Monthly Debts

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  generate-debts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Run Prisma Migrations
        run: npx prisma migrate deploy

      - name: Generate Monthly Debts
        env:
          APP_URL: ${{ secrets.APP_URL }}
          CRON_SECRET_KEY: ${{ secrets.CRON_SECRET_KEY }}
        run: |
          curl -X POST $APP_URL/api/cron/generate-monthly-debts \
          -H "Authorization: Bearer $CRON_SECRET_KEY" \
          -H "Content-Type: application/json"

      - name: Cleanup Testing Data (Opcional)
        if: always()
        run: |
          npx prisma migrate reset --force